version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      maven-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "org.seleniumhq.selenium:selenium-bom"
      - dependency-name: "org.apache.maven.plugins:maven-surefire-plugin"
        update-types:
          - "version-update:semver-minor"
      - dependency-name: "org.apache.maven.plugins:maven-failsafe-plugin"
        update-types:
          - "version-update:semver-minor"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "ci"
